# Generated by Django 5.1.4 on 2025-01-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_rename_account_portfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
    ]
