# Generated by Django 5.1.2 on 2025-01-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='links',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], default='employee', max_length=10),
            preserve_default=False,
        ),
    ]
